# cc = gcc
# CFLAGS = -g -I./
# SRCCLENINT = .

# all: out
# out: a.o
# 	${CC} ${CFLAGS} $^ -o a.out
# a.o: ${SRCCLEINT}/%.c
# 	${CC} ${CFLAGS} -c $< -o $@

# # clean:
# #     rm ./*.o
# #     rm ./*.out